/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpxAccordion {
        "contentCustom": boolean;
        "contentText": string;
        "contentTextTag": string;
        "gap": string;
        "headerCustom": boolean;
        "headerGap": string;
        "headerText": string;
        "headerTextTag": string;
        "iconIndicator": string;
        "styling": string;
    }
    interface SpxAnimate {
        "clipPath": string;
        "delay": number;
        "duration": number;
        "ease": string;
        "once": boolean;
        "opacity": number;
        "stagger": number;
        "target": string;
        "viewport": boolean;
        "viewportMarginBottom": string;
        "viewportMarginLeft": string;
        "viewportMarginRight": string;
        "viewportMarginTop": string;
        "x": string;
        "y": string;
    }
    interface SpxClassToggle {
        "local": string;
        "target": string;
        "toggle": string;
    }
    interface SpxEdit {
        "editable": boolean;
        "name": string;
        "outline": string;
        "outlineFocus": string;
        "placeholder": string;
        "placeholderColor": string;
        "placeholderOpacity": string;
        "styling": string;
        "type": string;
    }
    interface SpxEditButton {
        "background": string;
        "backgroundDiscard": string;
        "border": string;
        "borderRadius": string;
        "bottom": string;
        "boxShadow": string;
        "color": string;
        "fontSize": string;
        "gap": string;
        "left": string;
        "padding": string;
        "position": string;
        "right": string;
        "styling": string;
        "textDiscard": string;
        "textEdit": string;
        "textSave": string;
        "top": string;
        "zIndex": number;
    }
    interface SpxGroup {
    }
    interface SpxIcon {
        "icon": string;
        "type": string;
    }
    interface SpxLoader {
        "color": string;
        "speed": string;
    }
    interface SpxMasonry {
        "bpColumns": string;
        "bpColumnsObject": object;
        "bpGap": string;
        "columns": number;
        "gap": string;
        "imageSize": string;
        "images": string;
        "mobileFirst": boolean;
        /**
          * Wrapper for recalculation.
         */
        "recalc": () => Promise<void>;
        /**
          * Wrapper for reinit.
         */
        "restart": () => Promise<void>;
        "trueOrder": boolean;
        "useContainerForBreakpoints": boolean;
        "useOwnImageLoader": boolean;
        "waitForImages": boolean;
    }
    interface SpxMockup {
        "browserBackground": string;
        "browserUrlBarBackground": string;
        "browserUrlBarBorder": string;
        "type": string;
    }
    interface SpxNavigation {
        "childBorderRadius": string;
        "childGap": string;
        "childIndicatorGap": string;
        "childItemGap": string;
        "childPadding": string;
        "iconChild": string;
        "linkColor": string;
        "menu": string;
        "mobile": number;
        "parentItemGap": string;
        "styling": string;
    }
    interface SpxSnackbar {
        "animationDelay": string;
        "animationDuration": string;
        "background": string;
        "borderRadius": string;
        "bottom": string;
        "color": string;
        "fontSize": string;
        "padding": string;
        "styling": string;
        "text": string;
    }
}
declare global {
    interface HTMLSpxAccordionElement extends Components.SpxAccordion, HTMLStencilElement {
    }
    var HTMLSpxAccordionElement: {
        prototype: HTMLSpxAccordionElement;
        new (): HTMLSpxAccordionElement;
    };
    interface HTMLSpxAnimateElement extends Components.SpxAnimate, HTMLStencilElement {
    }
    var HTMLSpxAnimateElement: {
        prototype: HTMLSpxAnimateElement;
        new (): HTMLSpxAnimateElement;
    };
    interface HTMLSpxClassToggleElement extends Components.SpxClassToggle, HTMLStencilElement {
    }
    var HTMLSpxClassToggleElement: {
        prototype: HTMLSpxClassToggleElement;
        new (): HTMLSpxClassToggleElement;
    };
    interface HTMLSpxEditElement extends Components.SpxEdit, HTMLStencilElement {
    }
    var HTMLSpxEditElement: {
        prototype: HTMLSpxEditElement;
        new (): HTMLSpxEditElement;
    };
    interface HTMLSpxEditButtonElement extends Components.SpxEditButton, HTMLStencilElement {
    }
    var HTMLSpxEditButtonElement: {
        prototype: HTMLSpxEditButtonElement;
        new (): HTMLSpxEditButtonElement;
    };
    interface HTMLSpxGroupElement extends Components.SpxGroup, HTMLStencilElement {
    }
    var HTMLSpxGroupElement: {
        prototype: HTMLSpxGroupElement;
        new (): HTMLSpxGroupElement;
    };
    interface HTMLSpxIconElement extends Components.SpxIcon, HTMLStencilElement {
    }
    var HTMLSpxIconElement: {
        prototype: HTMLSpxIconElement;
        new (): HTMLSpxIconElement;
    };
    interface HTMLSpxLoaderElement extends Components.SpxLoader, HTMLStencilElement {
    }
    var HTMLSpxLoaderElement: {
        prototype: HTMLSpxLoaderElement;
        new (): HTMLSpxLoaderElement;
    };
    interface HTMLSpxMasonryElement extends Components.SpxMasonry, HTMLStencilElement {
    }
    var HTMLSpxMasonryElement: {
        prototype: HTMLSpxMasonryElement;
        new (): HTMLSpxMasonryElement;
    };
    interface HTMLSpxMockupElement extends Components.SpxMockup, HTMLStencilElement {
    }
    var HTMLSpxMockupElement: {
        prototype: HTMLSpxMockupElement;
        new (): HTMLSpxMockupElement;
    };
    interface HTMLSpxNavigationElement extends Components.SpxNavigation, HTMLStencilElement {
    }
    var HTMLSpxNavigationElement: {
        prototype: HTMLSpxNavigationElement;
        new (): HTMLSpxNavigationElement;
    };
    interface HTMLSpxSnackbarElement extends Components.SpxSnackbar, HTMLStencilElement {
    }
    var HTMLSpxSnackbarElement: {
        prototype: HTMLSpxSnackbarElement;
        new (): HTMLSpxSnackbarElement;
    };
    interface HTMLElementTagNameMap {
        "spx-accordion": HTMLSpxAccordionElement;
        "spx-animate": HTMLSpxAnimateElement;
        "spx-class-toggle": HTMLSpxClassToggleElement;
        "spx-edit": HTMLSpxEditElement;
        "spx-edit-button": HTMLSpxEditButtonElement;
        "spx-group": HTMLSpxGroupElement;
        "spx-icon": HTMLSpxIconElement;
        "spx-loader": HTMLSpxLoaderElement;
        "spx-masonry": HTMLSpxMasonryElement;
        "spx-mockup": HTMLSpxMockupElement;
        "spx-navigation": HTMLSpxNavigationElement;
        "spx-snackbar": HTMLSpxSnackbarElement;
    }
}
declare namespace LocalJSX {
    interface SpxAccordion {
        "contentCustom"?: boolean;
        "contentText"?: string;
        "contentTextTag"?: string;
        "gap"?: string;
        "headerCustom"?: boolean;
        "headerGap"?: string;
        "headerText"?: string;
        "headerTextTag"?: string;
        "iconIndicator"?: string;
        "styling"?: string;
    }
    interface SpxAnimate {
        "clipPath"?: string;
        "delay"?: number;
        "duration"?: number;
        "ease"?: string;
        "once"?: boolean;
        "opacity"?: number;
        "stagger"?: number;
        "target"?: string;
        "viewport"?: boolean;
        "viewportMarginBottom"?: string;
        "viewportMarginLeft"?: string;
        "viewportMarginRight"?: string;
        "viewportMarginTop"?: string;
        "x"?: string;
        "y"?: string;
    }
    interface SpxClassToggle {
        "local"?: string;
        "target"?: string;
        "toggle"?: string;
    }
    interface SpxEdit {
        "editable"?: boolean;
        "name"?: string;
        "outline"?: string;
        "outlineFocus"?: string;
        "placeholder"?: string;
        "placeholderColor"?: string;
        "placeholderOpacity"?: string;
        "styling"?: string;
        "type"?: string;
    }
    interface SpxEditButton {
        "background"?: string;
        "backgroundDiscard"?: string;
        "border"?: string;
        "borderRadius"?: string;
        "bottom"?: string;
        "boxShadow"?: string;
        "color"?: string;
        "fontSize"?: string;
        "gap"?: string;
        "left"?: string;
        "onSpxEditDiscardChanges"?: (event: CustomEvent<any>) => void;
        "onSpxEditSaveChanges"?: (event: CustomEvent<any>) => void;
        "padding"?: string;
        "position"?: string;
        "right"?: string;
        "styling"?: string;
        "textDiscard"?: string;
        "textEdit"?: string;
        "textSave"?: string;
        "top"?: string;
        "zIndex"?: number;
    }
    interface SpxGroup {
    }
    interface SpxIcon {
        "icon"?: string;
        "type"?: string;
    }
    interface SpxLoader {
        "color"?: string;
        "speed"?: string;
    }
    interface SpxMasonry {
        "bpColumns"?: string;
        "bpColumnsObject"?: object;
        "bpGap"?: string;
        "columns"?: number;
        "gap"?: string;
        "imageSize"?: string;
        "images"?: string;
        "mobileFirst"?: boolean;
        "onSpxMasonryDidLoad"?: (event: CustomEvent<any>) => void;
        "trueOrder"?: boolean;
        "useContainerForBreakpoints"?: boolean;
        "useOwnImageLoader"?: boolean;
        "waitForImages"?: boolean;
    }
    interface SpxMockup {
        "browserBackground"?: string;
        "browserUrlBarBackground"?: string;
        "browserUrlBarBorder"?: string;
        "type"?: string;
    }
    interface SpxNavigation {
        "childBorderRadius"?: string;
        "childGap"?: string;
        "childIndicatorGap"?: string;
        "childItemGap"?: string;
        "childPadding"?: string;
        "iconChild"?: string;
        "linkColor"?: string;
        "menu"?: string;
        "mobile"?: number;
        "parentItemGap"?: string;
        "styling"?: string;
    }
    interface SpxSnackbar {
        "animationDelay"?: string;
        "animationDuration"?: string;
        "background"?: string;
        "borderRadius"?: string;
        "bottom"?: string;
        "color"?: string;
        "fontSize"?: string;
        "padding"?: string;
        "styling"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "spx-accordion": SpxAccordion;
        "spx-animate": SpxAnimate;
        "spx-class-toggle": SpxClassToggle;
        "spx-edit": SpxEdit;
        "spx-edit-button": SpxEditButton;
        "spx-group": SpxGroup;
        "spx-icon": SpxIcon;
        "spx-loader": SpxLoader;
        "spx-masonry": SpxMasonry;
        "spx-mockup": SpxMockup;
        "spx-navigation": SpxNavigation;
        "spx-snackbar": SpxSnackbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spx-accordion": LocalJSX.SpxAccordion & JSXBase.HTMLAttributes<HTMLSpxAccordionElement>;
            "spx-animate": LocalJSX.SpxAnimate & JSXBase.HTMLAttributes<HTMLSpxAnimateElement>;
            "spx-class-toggle": LocalJSX.SpxClassToggle & JSXBase.HTMLAttributes<HTMLSpxClassToggleElement>;
            "spx-edit": LocalJSX.SpxEdit & JSXBase.HTMLAttributes<HTMLSpxEditElement>;
            "spx-edit-button": LocalJSX.SpxEditButton & JSXBase.HTMLAttributes<HTMLSpxEditButtonElement>;
            "spx-group": LocalJSX.SpxGroup & JSXBase.HTMLAttributes<HTMLSpxGroupElement>;
            "spx-icon": LocalJSX.SpxIcon & JSXBase.HTMLAttributes<HTMLSpxIconElement>;
            "spx-loader": LocalJSX.SpxLoader & JSXBase.HTMLAttributes<HTMLSpxLoaderElement>;
            "spx-masonry": LocalJSX.SpxMasonry & JSXBase.HTMLAttributes<HTMLSpxMasonryElement>;
            "spx-mockup": LocalJSX.SpxMockup & JSXBase.HTMLAttributes<HTMLSpxMockupElement>;
            "spx-navigation": LocalJSX.SpxNavigation & JSXBase.HTMLAttributes<HTMLSpxNavigationElement>;
            "spx-snackbar": LocalJSX.SpxSnackbar & JSXBase.HTMLAttributes<HTMLSpxSnackbarElement>;
        }
    }
}
